---
- hosts: all
  become: true
  vars:
    packages_to_install: [ 'kernel', 'kernel-headers', 'rubygems', '@development', 'gcc-c++', 'libvirt', 'libvirt-devel', 'ruby-devel', 'elfutils-libelf-devel']
    vagrant_plugins: ['vagrant-scp']
    vagrant_rpm_url: 'https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.rpm'
    virtualbox_rpm_url: 'https://download.virtualbox.org/virtualbox/6.1.8/VirtualBox-6.1-6.1.8_137981_el8-1.x86_64.rpm'

  tasks:
    - name: Update the whole system
      yum:
        name: '*'
        state: latest
      register: update_packages

    - name: reboot after update
      reboot:
      when: update_packages.changed

    - name: Wait for  system to boot up
      wait_for:
        port: 22
        delay: 15
        timeout: 100
      when: update_packages.changed

    - name: Install packages additional packages
      yum: 
        name: "{{packages_to_install}}"
        state: present

    - name: Install vagrant
      yum:
        name:  "{{vagrant_rpm_url}}"
        state: present
    
    - name: Install Virtualbox
      yum:
        name:  "{{virtualbox_rpm_url}}"
        state: present
    - name: Start and enable vboxdrv
      service:
        name: vboxdrv
        state: started
        enabled: true

    - name: Install vagrant plugins
      command: "vagrant plugin install {{item}}"
      loop: "{{vagrant_plugins}}"

    - name: reboot machine
      reboot:

    - name: Wait for  system to boot up
      wait_for:
        port: 22
        delay: 15
        timeout: 100
