---
- hosts: all
  become: true
  vars:
    packages_to_install: [ 'kernel', 'kernel-headers', 'rubygems', '@development', 'gcc-c++', 'libvirt', 'libvirt-devel', 'ruby-devel', 'qemu-kvm', 'epel-release']
    packages_for_qa: [ 'kernel', 'kernel-headers', 'rubygems', '@development', 'gcc-c++', 'libvirt', 'libvirt-devel', 'ruby-devel', 'qemu-kvm', 'epel-release']
    vagrant_plugins: ['vagrant-libvirt', 'vagrant-scp']
    vagrant_rpm_url: 'https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.rpm'
  tasks:
    - name: Update the whole system
      yum:
        name: '*'
        state: latest
      register: update_packages

    - name: reboot after update
      reboot:
      when: update_packages.changed

    - name: Wait for  system to boot up
      wait_for:
        port: 22
        delay: 15
        timeout: 100
      when: update_packages.changed

    - name: Install packages additional packages
      yum: 
        name: "{{packages_to_install}}"
        state: present

    - name: Enable libvirtd services 
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Install vagrant
      yum:
        name:  "{{vagrant_rpm_url}}"
        state: present

    - name: Install vagrant plugins
      command: "vagrant plugin install {{item}}"
      loop: "{{vagrant_plugins}}"

    - name: reboot machine
      reboot:

    - name: Wait for  system to boot up
      wait_for:
        port: 22
        delay: 15
        timeout: 100
